### PR TITLE
MERL-1342: removed logging of the telemetry in cli

### PR DESCRIPTION
**Pull request by matthewguywright**
## Description
Removed prompt and log for telemetry. All telemetry scaffolding is still in place but won't fire since they didn't enable telemetry at the cli level.

## Testing
Run the CLI and ensure no messaging for telemetry shows up in the logging.

### CODE REVIEW

**Review by mindctrl — CHANGES_REQUESTED** [review]
The lint_packages job failed due to the unused import of `infoLog`. The e2e tests failed too, but seems like a one-off thing.

**Review by blakewilson — CHANGES_REQUESTED** [review]
We have some unused dependencies now after removing telemetry stuff. We'll want to take care of that.

Other than that, looks good @matthewguywright!

**Comment by blakewilson** [comment]
@matthewguywright It looks like we'll need a changeset as well.

**Comment by blakewilson** [comment]
@matthewguywright It looks like `uuid` still exists as a dependency.

**Comment by matthewguywright** [comment]
Mergining to feature/mw-cli-api-v2

**Pull request closed without merging**
