### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by colorful-tones**
> community health files are a set of predefined files that provide guidance and templates for maintaining a healthy and collaborative open-source project.

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

### CODE REVIEW

**Comment by ChrisWiegman** [comment]
Is this a standard used throughout WP Engine or something else?

**Comment by colorful-tones** [comment]
> Is this a standard used throughout WP Engine or something else?

Unfortunately, there are no WP Engine GitHub organizational standards, which would typically be located at https://github.com/wpengine/.github.

The code of conduct standard is part of GitHub's [Building Communities](https://docs.github.com/en/communities) guide, which specifically has a guide for: [Adding a code of conduct to your project](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project). You can view a repository's Community Health Standards by choosing the 'Insights' tab at the top, and then 'Community Standards'. Here is a direct link to Faust's current Community Standards, which is where I submitted this request: https://github.com/wpengine/faustjs/community

This is all documented in the [Open Source Guides](https://opensource.guide/) > [Establishing a Code of Conduct](https://opensource.guide/code-of-conduct/#establishing-a-code-of-conduct).

Once you initialize submitting a request through this area of a repository, you're prompted with two template options: [Contributor Covenant](https://www.contributor-covenant.org/version/2/1/code_of_conduct/) and the [Citizen Code of Conduct](https://web.archive.org/web/20200330154000/http://citizencodeofconduct.org/) as possible options for consideration. I chose to submit the Contributor Convenant, as it is widely supported throughout the WordPress community.

Current Wordpress community projects that recognize the Contributor Convenent, or maintain derivatives of the Contributor Convenet are:

- Gutenberg Plugin: https://github.com/WordPress/gutenberg?tab=coc-ov-file
- WordPress Contributor Handbook - Community Code of Conduct
- 10up (a WP partner agency) https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md
- WPGraphQL organization's https://github.com/wp-graphql/wp-graphql/blob/develop/.github/CODE_OF_CONDUCT.md

**Comment by ChrisWiegman** [comment]
Thanks, @colorful-tones .

As this is organizational, I'm going to ask @jasonbahl and @theodesp to chime in here. For me I'm OK merging this.

**Review by theodesp — APPROVED** [review]
LGTM!

**Pull request merged**
