### PR TITLE
fix(cli): #1966 Migrates `glob-promise` dependency to Promise support…

### PR DESCRIPTION
**Pull request by diegoavalon**
[!IMPORTANT](https://www.npmjs.com/package/glob-promise)

Glob has native Promise support as of v9.0.0, please use it directly. I will not issue a deprecation notice on this package, because I can't deal with the volume of angry tickets that will follow.

### CODE REVIEW

**Comment by theodesp** [comment]
Hey @diegoavalon. Can you add `glob-promise` in package.json dev dependency as well please?

**Comment by diegoavalon** [comment]
hi @theodesp , `glob-promise` isn't being used in this package anymore and has been removed.

**Comment by theodesp** [comment]
@diegoavalon Could you also create a Changeset as well please? The instructions are mentioned in the [changeset-bot](https://github.com/apps/changeset-bot)

```
npm run changeset
```

**Comment by diegoavalon** [comment]
Hi @theodesp , my apologies, I see what I did wrong. After creating the changeset for this change I manually executed `npm changeset version` locally which bumped the affected package versions and deleted the generated changeset.md file. Instead, this should have been a CI step. Hopefully, this PR is now as expected. Can you kindly validate?

**Comment by theodesp** [comment]
Hey @diegoavalon thank you. 
Could you restore this file please?
https://github.com/wpengine/faustjs/pull/1967/files#diff-acbd6f841eb36512210b996294dcd4050a5febdb1fa023bb30c962f6c2707314

This is the changeset for another PR and it should be part of the folder as well.

**Comment by diegoavalon** [comment]
hi @theodesp , can you kindly review this new PR cut from a clean branch and commit history of these changes?
[PR #1966](https://github.com/wpengine/faustjs/pull/1980)

**Pull request closed without merging**
