### PR TITLE
Feat: InspectorFields component

### PR DESCRIPTION
**Pull request by theodesp**
## Tasks

- [ ] I have signed a [Contributor License Agreement (CLA)](https://github.com/wpengine/faustjs#contributor-license-agreement) with WP Engine.
- [ ] If a code change, I have written testing instructions that the whole team & outside contributors can understand.
- [ ] I have written and included a comprehensive [changeset](https://github.com/wpengine/faustjs/blob/canary/DEVELOPMENT.md#deployment) to properly document the changes I've made.

## Description
* Implements automatic handling of InspectorFields controls as per RFC document.
* Unit tests added

## Related Issue(s):
https://github.com/wpengine/faustjs/issues/1522

## Testing

1. run `npm install`
2. Build the project 
  `npm run build -w packages/block-editor-utils`
4. cd inside the project folder:
   `cd packages/block-editor-utils`
5. run `npm link`
6. On your WordPress instance create a new block plugin using [@wordpress/create-block](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-create-block/)
`npx @wordpress/create-block hello-world-block`
8. Inside the plugin folder run `npm link @faustwp/block-editor-utils ` to add a reference to the package.
9. Rewrite the genenated `index.js` editor script to use the `registerFaustBlock` helper function instead adding the hook for testing the controls
```js
// index.js
import { addFilter } from '@wordpress/hooks';
import "./style.scss";
// import block.json
import metadata from "./block.json";

// import Pure React Component
import HelloWorld from "./HelloWorld";

// Register React Component in Gutenberg
import { registerFaustBlock } from "@faustwp/block-editor-utils";

addFilter(
  'faustBlockEditorUtils.controls',
  'faust-block-editor-utils',
  (controls) => {
    controls.color = () => <div>Another Color</div>;
    return controls;
  },
);

registerFaustBlock(HelloWorld, { blockJson: metadata });
```
Here `HelloWorld` is a simple Div Component with the `editorFields` config that contains a color field

```jsx
// HelloWorld.js
function HelloWorld({ style, className, attributes, children, ...props }) {
	const styles = {
		...style,
		backgroundColor: attributes.bg_color,
		color: attributes.text_color,
	};
	return (
		<div
			{...props}
			style={styles}
			className={className}
			dangerouslySetInnerHTML={{ __html: attributes.message }}
		/>
	);
}

HelloWorld.config = {
	name: "HelloWorld",
        editorFields: {
		message: {
			type: "string",
			default: "",
			label: "My Message",
			location: "editor",
			control: "textarea",
		},
		bg_color: {
			location: "inspector",
			control: "color",
		},
	},
};
export default HelloWorld;

```

```json
// block.json
{
	"$schema": "https://schemas.wp.org/trunk/block.json",
	"apiVersion": 2,
	"name": "create-block/hello-world-block",
	"version": "0.1.0",
	"title": "Hello World Block",
	"category": "widgets",
	"icon": "smiley",
	"description": "Example block scaffolded with Create Block tool.",
	"supports": {
		"html": false
	},
	"attributes": {
		"message": {
			"type": "string",
			"default": "Hello World"
		},
		"bg_color": { "type": "string", "default": "#000000" }
	},
	"textdomain": "hello-world-block",
	"editorScript": "file:./index.js",
	"editorStyle": "file:./index.css",
	"style": "file:./style-index.css"
}

```

7) Run `npm start` to build the compiled js

8) Now go into the editor and try to create a new block. You should be able to see the Edit mode component. On the sidebar you can see the example color control component that we defined for testing purposes.

Screenshot 2023-08-30 at 16 55 01

### CODE REVIEW

**Comment by theodesp** [comment]
> Hey @theodesp,
> 
> I followed your testing instructions, but I'm not seeing the same thing. It looks like there are no new editor fields when I try and edit the block:
> 
> Screenshot 2023-08-29 at 9 13 29 AM Screenshot 2023-08-29 at 9 13 35 AM

The block fields should be available in the *Block* tab and not in the *Post* tab. Are there any console errors you can share?

**Comment by blakewilson** [comment]
@theodesp Nope, no console errors that stand out 🤔

**Review by matthewguywright — APPROVED** [review]
We ran through the testing steps with Theo during a meeting.

**Review by TeresaGobble — APPROVED** [review]
The panel body features "another Color" as expected. Still seeing the semi-colon, not sure how to remove that except for with a `ts-ignore` line above it and snipping it in the file `InspectorFields.tsx`, line 34.

image

**Pull request merged**
