### PR TITLE
Merl 1306 multiple queries

### PR DESCRIPTION
**Pull request by blakewilson**
## Tasks

- [x] I have signed a [Contributor License Agreement (CLA)](https://github.com/wpengine/faustjs#contributor-license-agreement) with WP Engine.
- [x] If a code change, I have written testing instructions that the whole team & outside contributors can understand.
- [x] I have written and included a comprehensive [changeset](https://github.com/wpengine/faustjs/blob/canary/DEVELOPMENT.md#deployment) to properly document the changes I've made.

## Description

This PR adds a new possible field on a Faust WordPress Template called `queries`. This property allows you to supply multiple queries and variables to one Faust Template.

## Testing

1. Checkout this branch
2. Build the packages `npm run build`
3. Start the example project `npm run dev -w @faustwp/getting-started-example`
4. Visit a `Single` post template and notice that the multiple queries are being resolved as expected.
5. Visit a `Page` template and notice that the singe query works as intended.
6. Visit a mix of both single posts and pages; trying previews for each, CSR, and regular SSG to look for any irregularities.
7. Try to break it. There are a number of changes in core Faust features here so we want to make sure there is no regression.

New unit tests for WordPressTemplate have been added.

### CODE REVIEW

**Comment by theodesp** [comment]
Some conflicts...

**Comment by theodesp** [comment]
@blakewilson looks good. I didn't find any issues. Lets get one more approval

**Review by theodesp — APPROVED** [review]

**Comment by mindctrl** [comment]
@blakewilson is this supposed to be a draft or is it ready for final review?

**Comment by blakewilson** [comment]
> @blakewilson is this supposed to be a draft or is it ready for final review?

This is now ready for review.

**Pull request merged**
