### PR TITLE
FaustNX Preview Support

### PR DESCRIPTION
**Pull request by blakewilson**
## Description

This PR introduces preview support in FaustNX.

## Testing

1. Ensure you have set you WordPress URL and Secret Key in the `.env.local`
2. Smoke test previews for pages/posts in both an already published and draft state.

### CODE REVIEW

**Comment by theodesp** [comment]
@blakewilson  when I try to preview a page I get this error:
Screenshot 2022-09-08 at 12 25 37

**Comment by theodesp** [comment]
> @blakewilson when I try to preview a page I get this error: Screenshot 2022-09-08 at 12 25 37

It seems like a query parameter is expected here:

Screenshot 2022-09-08 at 12 32 45

**Comment by blakewilson** [comment]
@theodesp Yes, there is a new query param that is added to the preview URL:

https://github.com/wpengine/faustjs/pull/1000/files#diff-e7d71bae262ad10f2716f4f695660a50636e3ee031f1302628ea825422cad5efR134

Is your FaustWP plugin pulling from the `merl-454-previews` branch as well?

**Review by theodesp — APPROVED** [review]
Works perfect. Thank you!

**Pull request merged**
