### PR TITLE
Feat: Added Blockset command (STALE)

### PR DESCRIPTION
**Pull request by theodesp**
## Tasks

- [ ] I have signed a [Contributor License Agreement (CLA)](https://github.com/wpengine/faustjs#contributor-license-agreement) with WP Engine.
- [ ] If a code change, I have written testing instructions that the whole team & outside contributors can understand.
- [ ] I have written and included a comprehensive [changeset](https://github.com/wpengine/faustjs/blob/canary/DEVELOPMENT.md#deployment) to properly document the changes I've made.

## Description

**STALE PR.  REVIEW https://github.com/wpengine/faustjs/pull/1585 INSTEAD**

### CODE REVIEW

**Comment by josephfusco** [comment]
Hey @theodesp, I appreciate you stepping in to fix the CI/CD pipeline issues in #1585!

Would it be possible to extract the unrelated changes into a separate PR please into canary please? This way, we can keep the commit history clean and ensure that both our contributions are accurately represented.

I believe that #1565 should be reviewed prior to #1585 work in order to keep a separation of concerns, with the `blockset` command being one feature that utilizes that example.

**Comment by theodesp** [comment]
> Hey @theodesp, I appreciate you stepping in to fix the CI/CD pipeline issues in #1585!
> 
> Would it be possible to extract the unrelated changes into a separate PR please into canary please? This way, we can keep the commit history clean and ensure that both our contributions are accurately represented.
> 
> I believe that #1565 should be reviewed prior to #1585 work in order to keep a separation of concerns, with the `blockset` command being one feature that utilizes that example.

I've approved the Block Support Example PR feel free to merge. I will remove any references of this from https://github.com/wpengine/faustjs/pull/1585!

**Comment by blakewilson** [comment]
@theodesp What is the best way to test this?

**Comment by theodesp** [comment]
> * Run npm run blockset -w @faustwp/block-support-example from the root of the monorepo.
> * Observe that wp-content/uploads/faustwp/blocks/ in your WordPress site now contains block-a & block-b.
> * Delete block-a from the Next.js application
> * Run npm run blockset -w @faustwp/block-support-example again
> * Observe that wp-content/uploads/faustwp/blocks/ now only contains block-b.

I've updated the testing instructions.

**Comment by TeresaGobble** [comment]
Hello Theo, thank you for your work on this! It's a tricky piece of the puzzle and your expertise on it is appreciated. 😊 

I'm having trouble getting the first step of testing to work for me. When I run the `npm run blockset -w @faustwp/block-support-example `from the root of the monorepo in the MERL-1235 branch, I receive the following error:

image

(Here is the same error in a code block for convenience:)

```
teresa.gobble@teresa-gobble faustjs % npm run blockset -w @faustwp/block-support-example

> @faustwp/block-support-example@0.1.0 blockset
> faust blockset

debug - Faust is running in debug mode
debug - Discoverd GraphQL endpoint at https://faustexample.wpengine.com/index.php?graphql
error - Invalid project directory provided, no such directory: /Users/teresa.gobble/Documents/GitHub/faustjs/examples/next/block-support/blockset
npm ERR! Lifecycle script `blockset` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @faustwp/block-support-example@0.1.0 
npm ERR!   at location: /Users/teresa.gobble/Documents/GitHub/faustjs/examples/next/block-support 
teresa.gobble@teresa-gobble faustjs % 
```

I have already run `npm i` and `npm run build` at the root level of the monorepo and at `block-support`, but I am not seeing a blockset file or folder populate inside the block-support folder. I also don't see the two blocks generated under my test repo's site in`wp-content/uploads/faustwp/blocks/` as the next step in the testing instructions says I would. Am I potentially missing a step?

**Comment by TeresaGobble** [comment]
Related to jest testing: when I run the install and build commands in the MERL-1235 branch at the root, I receive the following error: 

image

(Here is the same error in a code block for convenience:)
```
Jest (faustjs)

[info] auto config:

found:
  rootPath: /Users/teresa.gobble/Documents/GitHub/faustjs
  jestCommandLine: "/Users/teresa.gobble/Documents/GitHub/faustjs/node_modules/.bin/jest"

No tests found related to files changed since last commit.

> Test run started at 10/9/2023, 7:53:38 PM <



> Test run finished at 10/9/2023, 7:53:38 PM <

Assertion failed: (napi_call_function(env, recv, callback, 3, args, &recv) == napi_ok), function fse_dispatch_event, file fsevents.c, line 151.

[error] Jest process "watch-tests" ended unexpectedly

[info] jest test run failed, please see: https://github.com/jest-community/vscode-jest/blob/master/README.md#troubleshooting

> Test run exited at 10/9/2023, 7:53:48 PM <`
```

I haven't seen this error before- am I missing something here that needs to happen as a part of my testing workflow?

**Comment by TeresaGobble** [comment]
(Forgot to tag you, @theodesp ! )

**Pull request closed without merging**
