### PR TITLE
Chore: Update Block Support

### PR DESCRIPTION
**Pull request by theodesp**
## Tasks

- [ ] I have signed a [Contributor License Agreement (CLA)](https://github.com/wpengine/faustjs#contributor-license-agreement) with WP Engine.
- [ ] If a code change, I have written testing instructions that the whole team & outside contributors can understand.
- [ ] I have written and included a comprehensive [changeset](https://github.com/wpengine/faustjs/blob/canary/DEVELOPMENT.md#deployment) to properly document the changes I've made.

## Description

- Updates dependencies of Block Support example.
- Fixes issue with pages not rendering inner blocks.

## Testing

- Make sure you checkout this PR in Content Blocks: https://github.com/wpengine/wp-graphql-content-blocks/pull/182
- Install dependencies
```bash
npm i
```
- Delete to node_modules inside the block_support folder to avoid any issues with Multiple React Versions:

```bash
rm -rf examples/next/block-support/node_modules 
```

- Make sure you have setup a home page as a single page/post in WordPress Reading Settings:
Screenshot 2024-01-25 at 16 32 54

- Update the blockset command:

```
npm run blockset -w examples/next/block-support
```

- Run the project and you should be able to see the front-page without issues.

```bash
npm run dev -w examples/next/block-support
```

### CODE REVIEW

**Review by matthewguywright — DISMISSED** [review]

**Review by matthewguywright — APPROVED** [review]
After getting latest content blocks repo and running the blockset command this worked as expected. @theodesp Please update the instructions. Good job!

**Review by mindctrl — CHANGES_REQUESTED** [review]
I'm still seeing Apollo errors here, and I want to be sure I'm not doing something wrong. 
**Can you rewrite the testing instructions as if an outside contributor were needing to test this?**

Here's what I'm getting on the WP side, with the latest Content Blocks updates (not including the whole stack, as it's huge!).

```
PHP Warning:  Undefined array key "isStackedOnMobile" in wp-graphql-content-blocks/includes/Blocks/Block.php on line 422
```

Screenshot of my test page in the editor:
image

**Comment by theodesp** [comment]
@mindctrl thanks. I think this is related to some bugs with [the PR](https://github.com/wpengine/wp-graphql-content-blocks/pull/176) in  `wpgraphql-content-blocks` plugin and not so with this project.
I will take a look.

**Comment by theodesp** [comment]
@mindctrl @mindctrl I've added a bug fix for the content-blocks

https://github.com/wpengine/wp-graphql-content-blocks/pull/182

**Review by mindctrl — APPROVED** [review]

**Comment by mindctrl** [comment]
We have a merge conflict now

**Pull request merged**
