### PR TITLE
BH-744 Consolidates URL settings into a single option.

### PR DESCRIPTION
**Pull request by mindctrl**
chore: Consolidate URL settings into single field.

chore: Remove unused Events setting.

chore: Simplify settings page design.

This removes `replacement_domain` and moves the functionality to the `frontend_uri` setting.

It also removes the settings section headings to simplify the design, per feedback from Trevan. The sections are still there, just not displaying a heading. The thinking there is we'll use these sections for visual separation once we have a final page design.

Also removes the Events setting. We can add it back later if needed.

### CODE REVIEW

**Comment by mindctrl** [comment]
Screenshot before
image


Screenshot after
image

**Review by rfmeier — APPROVED** [review]
Much much better. Thanks, @mindctrl !

**Comment by rfmeier** [comment]
>Also removes the Events setting. We can add it back later if needed.
I keep forgetting to ask about removing this. It may be way down the road before this gets used.

**Comment by mindctrl** [comment]
I have some uncommitted changes for updating the docs. Preference for putting them in this PR or in a follow up?

**Comment by basecardhero** [comment]
@mindctrl 

>I have some uncommitted changes for updating the docs. Preference for putting them in this PR or in a follow up?

Are they for the settings? I see no harm in including them here.

**Comment by rfmeier** [comment]
@mindctrl 

>I have some uncommitted changes for updating the docs. Preference for putting them in this PR or in a follow up?

Here is good.

**Comment by mindctrl** [comment]
@rfmeier thanks. I updated the docs and screenshot.

**Review by rfmeier — APPROVED** [review]

**Review by nickcernis — APPROVED** [review]
Much cleaner. Nice work!

**Pull request merged**
