### PR TITLE
MERL-1185: Redirect Off Doesn't Rewrite Post Preview Link

### PR DESCRIPTION
**Pull request by matthewguywright**
## Description
Updated post preview link to only rewrite if enable redirects is off.

## Testing
1. Setup a WP instance with Faust
2. Ensure the FaustWP Plugin is linked or installed correctly
3. In Faust Plugin, make sure `Enable public route redirects` is unchecked
4. Clicking preview in a post should work properly using Wordpress default post preview link

### CODE REVIEW

**Comment by blakewilson** [comment]
@matthewguywright Looks like there is some plugin tests failing

**Review by blakewilson — CHANGES_REQUESTED** [review]
LGTM! This needs a changeset though. Would this be considered a breaking change?

**Comment by theodesp** [comment]
@matthewguywright some conflicts there

**Review by TeresaGobble — COMMENTED** [review]
Hi Matt, nice work with this. I checked to ensure the redirect is still working when both unchecked and checked. All seems to be operating smoothly. LGTM!

**Review by TeresaGobble — APPROVED** [review]

**Pull request merged**
