### PR TITLE
Fix/get config in fetch access token

### PR DESCRIPTION
**Pull request by perrywortman**
## Tasks

- [x] I have signed a [Contributor License Agreement (CLA)](https://github.com/wpengine/faustjs#contributor-license-agreement) with WP Engine.
- [x] If a code change, I have written testing instructions that the whole team & outside contributors can understand.
- [x] I have written and included a comprehensive [changeset](https://github.com/wpengine/faustjs/blob/canary/DEVELOPMENT.md#deployment) to properly document the changes I've made.

## Description

This PR is a follow up to #1290 

Looks like we are calling getConfig and destructuring basePath at the top of packages/faustwp-core/src/auth/client/accessToken.ts before the config actually has a chance to load. Because of that basePath will be undefined since we will be using the defaults from normalizeConfig in packages/faustwp-core/src/config/index.ts.

To prevent this from happening, we can just move the call to getConfig and ref to basePath inside of fetchAccessToken

UPDATE: I was playing around with the experimental toolbar locally and noticed that the logout feature was 404ing. Seemed related to the basePath issue so I went ahead and prefixed all instances of api routes with the basePath and it fixed this issue as well. It's also possible that [this issue](https://github.com/wpengine/faustjs/issues/1429) might be related and solved by this fix.

## Related Issue(s):

- #1287  

## Testing

Tests were done locally by configuring `basePath` in `next.config.js` and `faust.config.js`.

### CODE REVIEW

**Comment by theodesp** [comment]
Hey @perrywortman Thanks. Could you also create a changeset as well?

From root folder:
```
npm run changeset
```

* Choose `@faustwp/core`
* Select Patch update.
* Enter short Patch message.

**Comment by perrywortman** [comment]
> Hey @perrywortman Thanks. Could you also create a changeset as well?
> 
> From root folder:
> 
> ```
> npm run changeset
> ```
> 
> * Choose `@faustwp/core`
> * Select Patch update.
> * Enter short Patch message.

Hi @theodesp Happy to add if needed but I thought I already did [here](https://github.com/wpengine/faustjs/pull/1479/commits/728a43e6d4b249246d7d0b95574a58a2d9875856).

**Comment by mindctrl** [comment]
@perrywortman thank you for this PR! This is on our list to do and we'll review sometime within the next week.

**Comment by perrywortman** [comment]
Hi @mindctrl, just checking on timeline for this PR getting merged in. Thanks!

**Comment by mindctrl** [comment]
@perrywortman this is in our current sprint. We'll see some movement here soon. Thanks for your patience!

**Review by josephfusco — APPROVED** [review]
This looks good to me, thanks again for your contribution @perrywortman!

**Pull request merged**
