### PR TITLE
[Merl-373] Tree Shaking fixed for @gqty/logger import

### PR DESCRIPTION
**Pull request by theodesp**
## Description

This PR adds few tree shaking improvements that affect the final build bundle size for both dev and prod environments. More specifically  it fixes the import side-effect when importing the `@gqty/logger`package and changes some of the lodash imports to be consistent.

## Related Issue(s):

https://github.com/wpengine/faustjs/issues/917

## Testing
1. Include the following config in `next/getting-started` example:

```
const { withFaust } = require('@faustjs/next');
const withBundleAnalyzer = require('@next/bundle-analyzer')({
  enabled: true
})

/**
 * @type {import('next').NextConfig}
 **/
module.exports = withFaust( withBundleAnalyzer({}));

```

Add the dependency to the package.json (do not use `npm install` as it will mess up the dependencies)

`"@next/bundle-analyzer": "12.2.3"`

2. From the root of folder run npm run:
`npm run install`
`npm run build`

3. Navigate to the `next/getting-started` example and run the production build:
`npm run build`

4. You should see the webpack analyser report for both the client and server side. You should not see any references to `@gqty/logger`. You will see a reference to lodash that is tree-shaked and is about 4kb gzipped.

*Note*

The dev build may contain references to `lodash` or `@gqty/logger` as they are not tree shaked.

## Screenshots

Dev Build
Screenshot 2022-07-20 at 11 32 45

Prod Build
Screenshot 2022-07-20 at 13 18 36

### CODE REVIEW

**Comment by josephfusco** [comment]
@theodesp I am still seeing @gqty/logger in the production build. I am running `npm run build` from within `faustjs/examples/next/getting-started`

**Comment by theodesp** [comment]
> @theodesp I am still seeing @gqty/logger in the production build. I am running `npm run build` from within `faustjs/examples/next/getting-started`

@josephfusco I think you need to remove the node modules within inside the root folder and install the dependencies again.

**Comment by theodesp** [comment]
@josephfusco Try again as I was missing some important config there.

**Comment by josephfusco** [comment]
@theodesp I cleaned up `node_modules` and tried again with the latest updates. Still seeing @gqty/logger. Maybe I am doing something wrong?

Here is my generated client.html for reference
[client.html.zip](https://github.com/wpengine/faustjs/files/9169993/client.html.zip)

**Review by josephfusco — APPROVED** [review]

**Comment by ivan-dalmet** [comment]
Hello @theodesp I see that this is merged! 🎉 
Nice job!
Any idea when this will be released?
Thanks for the work here!!

**Pull request merged**
