### PR TITLE
Add next-secure-headers in example projects

### PR DESCRIPTION
**Pull request by theodesp**
## Tasks

- [ ] I have signed a [Contributor License Agreement (CLA)](https://github.com/wpengine/faustjs#contributor-license-agreement) with WP Engine.
- [ ] If a code change, I have written testing instructions that the whole team & outside contributors can understand.
- [ ] I have written and included a comprehensive [changeset](https://github.com/wpengine/faustjs/blob/canary/DEVELOPMENT.md#deployment) to properly document the changes I've made.

## Description

Adds `next-secure-headers` in all example projects, providing secure default header configuration across the site.

## Testing

-Build and run one of the example projects
-Inspect the response headers of each page. It should have the following headers as defined in the [package doc](https://github.com/jagaapple/next-secure-headers?tab=readme-ov-file#next-secure-headers-vs-helmet)

|                                   | next-secure-headers     | Helmet                  | Comment                                                                                           |
|-----------------------------------|-------------------------|-------------------------|---------------------------------------------------------------------------------------------------|
| Strict-Transport-Security         | `forceHTTPSRedirect`    | `hsts`                  |                                                                                                   |
| X-Frame-Options                   | `frameGuard`            | `frameguard`            |                                                                                                   |
| X-Download-Options                | `noopen`                | `ieNoOpen`              |                                                                                                   |
| X-Content-Type-Options            | `nosniff`               | `noSniff`               |                                                                                                   |
| X-XSS-Protection                  | `0`         | `xssFilter`             |                                                                                                   |
| Content-Security-Policy           | `contentSecurityPolicy` | `contentSecurityPolicy` |                                                                                                   |
| Expect-CT                         | `expectCT`              | `expectCt`              |                                                                                                   |
| Referrer-Policy                   | `referrerPolicy`        | `referrerPolicy`        |                                                                                                   |
| X-DNS-Prefetch-Control            | -                       | `dnsPrefetchControl`    | This has privacy implications but this improves performance.                                      |
| Feature-Policy                    | -                       | `featurePolicy`         | Feature Policy improves security but it is working draft yet.                                     |
| X-Powered-By                      | -                       | `hidePoweredBy`         | [Next.js supports to remove this header in `next.config.js`](#how-to-remove-x-powered-by-header). |
| Related to cache                  | -                       | `nocache`               | As Helmet said, caching has lots of benefits.                                                     |
| X-Permitted-Cross-Domain-Policies | -                       | `crossdomain`           | Adobe Flash is one of old web technologies.                                                       |

### CODE REVIEW

**Review by blakewilson — CHANGES_REQUESTED** [review]
There's a merge conflict with `package-lock.json`

**Comment by blakewilson** [comment]
I'm unable to see the new headers after checking out this branch, npm installing, and building the example projects. Tried it on examples using the `pages` and `app` router to no avail.

Here's a screenshot:
Screenshot 2024-02-21 at 12 02 42 PM

Am I missing anything?

**Comment by theodesp** [comment]
> I'm unable to see the new headers after checking out this branch, npm installing, and building the example projects. Tried it on examples using the `pages` and `app` router to no avail.
> 
> Here's a screenshot: Screenshot 2024-02-21 at 12 02 42 PM
> 
> Am I missing anything?

I've updated the config. It should work now

Screenshot 2024-02-22 at 13 31 08

**Comment by mindctrl** [comment]
The `next-secure-headers` package hasn't been updated in 3+ years and it seems like the maintainer isn't around. Any concerns with that?

**Comment by theodesp** [comment]
> The `next-secure-headers` package hasn't been updated in 3+ years, and it seems like the maintainer isn't around. Any concerns with that?

I don't think so since this package has no real dependencies and it's written in such a way that it returns an object that next uses for the Headers configuration.

**Comment by mindctrl** [comment]
@theodesp thanks. It's not clear from the original post what exactly we should be seeing in the headers. You gave a table of values, but they're not all in the response, and the ones that are don't necessarily match the values you gave. For example, in your screenshot the value of `X-Frame-Options` doesn't match what's in the table. Can you clarify the expectations here?

**Comment by theodesp** [comment]
> @theodesp thanks. It's not clear from the original post what exactly we should be seeing in the headers. You gave a table of values, but they're not all in the response, and the ones that are don't necessarily match the values you gave. For example, in your screenshot the value of `X-Frame-Options` doesn't match what's in the table. Can you clarify the expectations here?

It should be:

|                                   | next-secure-headers     | 
|-----------------------------------|-------------------------|
| Strict-Transport-Security         | `max-Age: <2 years in seconds>`    |  |
| X-Frame-Options                   | `DENY`           | |
| X-Download-Options                | `noopen`                |  |                                                                                                   |
| X-Content-Type-Options            | `nosniff`               |  |                                                                                                   |
| X-XSS-Protection                  | `xssProtection`         | |                                                                                                   |
| Referrer-Policy                   | `strict-origin-when-cross-origin`        |  |

**Comment by mindctrl** [comment]
@theodesp LGTM. The only difference I see between what you provided in the table and what I see the headers is the value for `X-XSS-Protection`. I see a `1` for that instead of `xssProtection`. Looking at the MDN docs for X-XSS-Protection, it says not to use it in production. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection

image

**Comment by theodesp** [comment]
> @theodesp LGTM. The only difference I see between what you provided in the table and what I see the headers is the value for `X-XSS-Protection`. I see a `1` for that instead of `xssProtection`. Looking at the MDN docs for X-XSS-Protection, it says not to use it in production. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection
> 
> image

I've set this to false now

```
xssProtection: false
```

**Review by mindctrl — APPROVED** [review]

**Comment by theodesp** [comment]
@blakewilson merging is blocked until there is approval for the changeset.

**Comment by mindctrl** [comment]
@theodesp I dismissed Blake's review as stale, since you addressed it. No blockers to merge if you're happy with this.

**Pull request merged**
