### PR TITLE
feat(BH-863): add support for previewing drafts

### PR DESCRIPTION
**Pull request by claygriffiths**
Before this PR, previewing drafts was not possible. You could only preview autosaves of already published content.

Most of the changes revolve around the fact that `nodeByUri` does not support unpublished content so we need to fallback to `contentNode`. 

When previewing unpublished content, the format is `domain/draft/preview/REVISION_ID`. Unlike previewing published content, the ID after `/preview` **is** used. 

### Todo

* Gutenberg preview link support. I'm currently having trouble filtering this link. Related issues: https://github.com/WordPress/gutenberg/issues/13998 & https://github.com/WordPress/gutenberg/issues/4555

### CODE REVIEW

**Comment by mindctrl** [comment]
@claygriffiths are you seeing the 404 page flash just before the draft post content is rendered?


https://user-images.githubusercontent.com/1254870/106965968-79795880-6712-11eb-8647-9cdbb14ff5f0.mov

**Comment by nickcernis** [comment]
I see only the 404 template (served with a 200 status) for previews of drafts and non-drafts in the Classic Editor. I don't see a refresh to the preview content like John does.

The generated preview URL for a draft looks like `http://localhost:3000/?p=57008/preview/57008`.

The request and response in GraphiQL for the post I'm previewing look like this:

```
query GetContentNode($id: ID!, $idType: ContentNodeIdTypeEnum, $asPreview: Boolean) {
  contentNode(id: $id, idType: $idType, asPreview: $asPreview) {
    ... on Post {
      id
      slug
      title
      content
      isRevision
      isPreview
      isSticky
      excerpt
      templates
      uri
      status
      featuredImage {
        node {
          id
          altText
          sourceUrl
        }
      }
      preview {
        node {
          id
          slug
          title
          content
          isRevision
          isPreview
          isSticky
          excerpt
          uri
          templates
          status
          featuredImage {
            node {
              id
              altText
              sourceUrl
            }
          }
        }
      }
      enqueuedStylesheets {
        nodes {
          src
          handle
        }
      }
    }
    ... on Page {
      id
      slug
      title
      content
      isPreview
      isRevision
      isFrontPage
      isPostsPage
      uri
      status
      templates
      featuredImage {
        node {
          id
          altText
          sourceUrl
        }
      }
      preview {
        node {
          id
          slug
          title
          content
          isPreview
          isRevision
          isFrontPage
          isPostsPage
          uri
          status
          templates
          featuredImage {
            node {
              id
              altText
              sourceUrl
            }
          }
        }
      }
      enqueuedStylesheets {
        nodes {
          src
          handle
        }
      }
    }
  }
}
```

vars:

```
{
          "asPreview": true,          
          "id": 57008,
          "idType": "DATABASE_ID"
}
```

response:

```
{
  "data": {
    "contentNode": {
      "id": "cG9zdDo1NzAwOQ==",
      "slug": "57008-revision-v1",
      "title": "Test Previews",
      "content": "<p>Test Previews</p>\n",
      "isRevision": true,
      "isPreview": true,
      "isSticky": false,
      "excerpt": "<p>Test Previews</p>\n",
      "templates": [
        "single-revision-57008-revision-v1",
        "single-revision",
        "single",
        "singular",
        "index"
      ],
      "uri": "http://localhost:3000/api/auth/wpe-headless?redirect_uri=draft%2Fpreview%2F57008",
      "status": "inherit",
      "featuredImage": null,
      "preview": null,
      "enqueuedStylesheets": {
        "nodes": [
          {
            "src": "/wp-includes/css/dist/block-library/style.css",
            "handle": "wp-block-library"
          },
          {
            "src": "https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,400i,600,700&display=swap",
            "handle": "genesis-sample-fonts"
          },
          {
            "src": "/wp-includes/css/dashicons.css",
            "handle": "dashicons"
          },
          {
            "src": "http://dev.test/wp-content/themes/genesis-sample/lib/gutenberg/front-end.css",
            "handle": "genesis-sample-gutenberg"
          }
        ]
      }
    }
  },
  "extensions": {
    "debug": []
  }
}
```

**Comment by nickcernis** [comment]
### Classic Editor 

🟢   **Unpublished drafts** — preview as expected. I can't reproduce the 404 flicker page that John describes. (I also tried with slow network emulation.) URL looks like `http://localhost:3000/test-10/preview/56862` for me.

🔴   **Published posts** — I found a scenario where previews of published posts result in the 404 template if the Classic Editor is in focus when you click “Preview Changes”:
1. Create a post and publish it.
2. Click inside the Classic Editor to give it focus.
3. Click “Preview Changes”.

You'll see the 404 page.

The “preview changes” URL looks like this for me whether or not the editor is in focus:

http://localhost:3000/api/auth/wpe-headless?redirect_uri=new-post-2%2Fpreview%2F57027

When the editor is in focus, the redirect_uri redirects to:

`http://localhost:3000/new-post-2?_thumbnail_id=-1%2Fpreview%2F57027`

…giving the 404.

When the editor is not in focus, the redirect_uri redirects to:

`http://localhost:3000/new-post-2/preview/57027`

...loading the preview as expected.

This does not appear to affect drafts or Gutenberg.

This also happens on canary, so is not specific to this PR.

### Gutenberg

🟢 **Published posts** — preview as expected.
[Didn't try draft due to known issues you described.]

**Comment by mindctrl** [comment]
@nickcernis good catch on the published post preview issue where the URL ends up being something like `?_thumbnail_id=-1%2Fpreview%2F114`. I see the same.

**Comment by claygriffiths** [comment]
@mindctrl Nice catch!

I am seeing that flicker if client-side queries are enabled using `NEXT_PUBLIC_WORDPRESS_URL` instead of `WORDPRESS_URL`. However, if I click the preview button from WordPress again to set the Next.js preview cookie, the flicker goes away.

**Review by nickcernis — APPROVED** [review]

**Review by nickcernis — COMMENTED** [review]
There's a conflict (from the recent paths PR) but this otherwise looks good!

**Review by mindctrl — APPROVED** [review]
LGTM now. There's a merge conflict here now though.

**Pull request merged**
