### PR TITLE
Fix CPT URL Rewrites

### PR DESCRIPTION
**Pull request by dana-blackbean**
## Tasks

- [x] I have signed a [Contributor License Agreement (CLA)](https://github.com/wpengine/faustjs#contributor-license-agreement) with WP Engine.
- [x] If a code change, I have written testing instructions that the whole team & outside contributors can understand.
- [x] I have written and included a comprehensive [changeset](https://github.com/wpengine/faustjs/blob/canary/DEVELOPMENT.md#deployment) to properly document the changes I've made.

## Description

When the option "Enable Post and Category URL rewrites" is turned on currently there is no check for any custom post types. This feature will currently only work on the default pages & posts.

## Testing

1. Create a custom post type using ACF or similar that is public (Visible on the frontend and in the admin dashboard.)
2. Ensure the Faust option "Enable Post and Category URL rewrites" is enabled
3. From the `canary` branch, create a new post in that custom post type.
4. Once created, inspect the "view" link in the post list. This should match the WordPress URL
    Screenshot 2024-01-26 at 8 47 49 AM
5. Now, checkout this PR
6. Visit the same custom post type list again, and notice the view link is now using the headless site url
    Screenshot 2024-01-26 at 8 47 40 AM

### CODE REVIEW

**Comment by theodesp** [comment]
Hey @dana-blackbean thank you for the PR. Could you also provide a unit test for this filter?

You need to add test case to verify that the filter exists in the following file:

plugins/faustwp/tests/integration/ReplacementCallbacksTests.php

**Comment by dana-blackbean** [comment]
@theodesp added!

**Comment by mindctrl** [comment]
@dana-blackbean thank you for this PR and apologies for the delay. We'll get this merged soon.

**Comment by mindctrl** [comment]
@dana-blackbean could you bring this up to date with canary? I tried but it wouldn't let me for some reason. Not sure if you're [allowing edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) or if it's something else.

**Comment by dana-blackbean** [comment]
@mindctrl I am also running into the same issue with merging with canary. I was able to merge with the upstream/canary. I have also checked "allowing edits from maintainers". It was never disabled so not sure why you were weren't able to make changes.

**Comment by blakewilson** [comment]
We can ignore the `Next.js Bundle Analysis / analyze` workflow failure. This will fail from any PR contributor outside of the GitHub team.

**Review by mindctrl — APPROVED** [review]

**Comment by mindctrl** [comment]
Thank you @dana-blackbean! This will be in our next release.

**Comment by blakewilson** [comment]
@dana-blackbean This just landed in [faustwp@1.2.1](https://github.com/wpengine/faustjs/releases/tag/%40faustwp%2Fwordpress-plugin%401.2.1). Thank you for your contribution!

**Comment by dana-blackbean** [comment]
@blakewilson @mindctrl Thank you both!!

**Pull request merged**
